apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
kind: StorageCLass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
  namespace: monitoring
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd