apiVersion: v1
kind: Namespace
metadata:
  name: automation-challenge
---
kind: StorageCLass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
  namespace: automation-challenge
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd